<METHOD_START> @ Test public void void ( ) java.sql.SQLException { assertThat ( this . org.springframework.boot.jdbc.ApplicationContext . getBeansOfType ( javax.sql.DataSource .class ) ) . hasSize ( NUMBER ) ; javax.sql.DataSource javax.sql.DataSource = this . org.springframework.boot.jdbc.ApplicationContext . getBean ( javax.sql.DataSource .class ) ; assertThat ( this . org.springframework.boot.jdbc.ApplicationContext . getBean ( STRING ) ) . isSameAs ( javax.sql.DataSource ) ; assertThat ( javax.sql.DataSource . java.sql.Connection ( ) . java.sql.DatabaseMetaData ( ) . java.lang.String ( ) ) . startsWith ( STRING ) ; BasicDataSource org.springframework.boot.jdbc.BasicDataSource = this . org.springframework.boot.jdbc.ApplicationContext . getBean ( STRING , BasicDataSource .class ) ; assertThat ( org.springframework.boot.jdbc.BasicDataSource . getUrl ( ) ) . isEqualTo ( STRING ) ; assertThat ( org.springframework.boot.jdbc.BasicDataSource . getMaxTotal ( ) ) . isEqualTo ( NUMBER ) ; }  <METHOD_END>
